import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiCheck,
  HiOutlineSun,
  HiOutlineMoon,
  HiMiniQuestionMarkCircle,
  HiMiniMinus,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMiniPlus,
  HiMiniUser,
  HiMiniXMark,
  HiEyeDropper,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiCalendar,
  HiOutlineLink,
  HiExclamationTriangle,
  HiArrowUpRight,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineBars3BottomLeft,
  HiOutlineHome,
  HiOutlineComputerDesktop,
  HiOutlineAcademicCap,
  HiOutlineInformationCircle,
  HiOutlineQuestionMarkCircle,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineIdentification,
  HiOutlinePhoto,
  HiOutlineMap,
  HiOutlineClock,
} from "react-icons/hi2";

import { RiVisaLine } from "react-icons/ri";

import { FaDiscord, FaGithub, FaGoogle, FaLinkedin, FaThreads } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  check: HiCheck,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  computer: HiOutlineComputerDesktop,
  helpCircle: HiOutlineQuestionMarkCircle,
  infoCircle: HiOutlineInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  eyeDropper: HiEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiMiniUser,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  document: HiOutlineBars3BottomLeft,
  linkedin: FaLinkedin,
  threads: FaThreads,
  home: HiOutlineHome,
  scholar: HiOutlineAcademicCap,
  queue: HiOutlineQueueList,
  rocket: HiOutlineRocketLaunch,
  card: HiOutlineIdentification,
  image: HiOutlinePhoto,
  roadmap: HiOutlineMap,
  changelog: HiOutlineClock
};
